// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmaBxyHib1_tWkxisOQhCHrD7VrEdOSw',
    appId: '1:1002466229581:web:6458ce32055e16adac8b04',
    messagingSenderId: '1002466229581',
    projectId: 'ret-vrn-4a12a',
    authDomain: 'ret-vrn-4a12a.firebaseapp.com',
    storageBucket: 'ret-vrn-4a12a.firebasestorage.app',
    measurementId: 'G-E7D8M9KDXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVq_mdPoiajnf9u9mQ6umP71NGyqajfBs',
    appId: '1:1002466229581:android:56c377c7dd8a53d2ac8b04',
    messagingSenderId: '1002466229581',
    projectId: 'ret-vrn-4a12a',
    storageBucket: 'ret-vrn-4a12a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJRwNfKGNHPkLazzU-JrTkHunxGWZj7s',
    appId: '1:1002466229581:ios:7d78396cd24d4597ac8b04',
    messagingSenderId: '1002466229581',
    projectId: 'ret-vrn-4a12a',
    storageBucket: 'ret-vrn-4a12a.firebasestorage.app',
    iosBundleId: 'com.example.ret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJRwNfKGNHPkLazzU-JrTkHunxGWZj7s',
    appId: '1:1002466229581:ios:7d78396cd24d4597ac8b04',
    messagingSenderId: '1002466229581',
    projectId: 'ret-vrn-4a12a',
    storageBucket: 'ret-vrn-4a12a.firebasestorage.app',
    iosBundleId: 'com.example.ret',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZmaBxyHib1_tWkxisOQhCHrD7VrEdOSw',
    appId: '1:1002466229581:web:6e1134241e517b30ac8b04',
    messagingSenderId: '1002466229581',
    projectId: 'ret-vrn-4a12a',
    authDomain: 'ret-vrn-4a12a.firebaseapp.com',
    storageBucket: 'ret-vrn-4a12a.firebasestorage.app',
    measurementId: 'G-M90E340S8C',
  );
}
